//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.20 at 09:11:46 AM EEST 
//


package fi.vm.yti.terminology.api.model.ntrf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FOREWORDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FOREWORDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HLANG" type="{}HLANGType"/>
 *         &lt;element name="LINK" type="{}LINKType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FOREWORDType", propOrder = {
    "hlang",
    "link"
})
public class FOREWORDType {

    @XmlElement(name = "HLANG", required = true)
    protected HLANGType hlang;
    @XmlElement(name = "LINK", required = true)
    protected LINKType link;

    /**
     * Gets the value of the hlang property.
     * 
     * @return
     *     possible object is
     *     {@link HLANGType }
     *     
     */
    public HLANGType getHLANG() {
        return hlang;
    }

    /**
     * Sets the value of the hlang property.
     * 
     * @param value
     *     allowed object is
     *     {@link HLANGType }
     *     
     */
    public void setHLANG(HLANGType value) {
        this.hlang = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link LINKType }
     *     
     */
    public LINKType getLINK() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link LINKType }
     *     
     */
    public void setLINK(LINKType value) {
        this.link = value;
    }

}
