//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.20 at 09:11:46 AM EEST 
//


package fi.vm.yti.terminology.api.model.ntrf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HEADERType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HEADERType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TITLES" type="{}TITLESType"/>
 *         &lt;element name="SERIAL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="YEAR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WORKGROUP" type="{}WORKGROUPType"/>
 *         &lt;element name="FINANCIERS" type="{}FINANCIERSType"/>
 *         &lt;element name="COMMENTS" type="{}COMMENTSType"/>
 *         &lt;element name="FOREWORD" type="{}FOREWORDType"/>
 *         &lt;element name="INDEX" type="{}INDEXType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="trackChanges" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HEADERType", propOrder = {
    "titles",
    "serial",
    "year",
    "workgroup",
    "financiers",
    "comments",
    "foreword",
    "index"
})
public class HEADERType {

    @XmlElement(name = "TITLES", required = true)
    protected TITLESType titles;
    @XmlElement(name = "SERIAL", required = true)
    protected String serial;
    @XmlElement(name = "YEAR", required = true)
    protected String year;
    @XmlElement(name = "WORKGROUP", required = true)
    protected WORKGROUPType workgroup;
    @XmlElement(name = "FINANCIERS", required = true)
    protected FINANCIERSType financiers;
    @XmlElement(name = "COMMENTS", required = true)
    protected COMMENTSType comments;
    @XmlElement(name = "FOREWORD", required = true)
    protected FOREWORDType foreword;
    @XmlElement(name = "INDEX", required = true)
    protected INDEXType index;
    @XmlAttribute(name = "trackChanges")
    protected String trackChanges;

    /**
     * Gets the value of the titles property.
     * 
     * @return
     *     possible object is
     *     {@link TITLESType }
     *     
     */
    public TITLESType getTITLES() {
        return titles;
    }

    /**
     * Sets the value of the titles property.
     * 
     * @param value
     *     allowed object is
     *     {@link TITLESType }
     *     
     */
    public void setTITLES(TITLESType value) {
        this.titles = value;
    }

    /**
     * Gets the value of the serial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERIAL() {
        return serial;
    }

    /**
     * Sets the value of the serial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERIAL(String value) {
        this.serial = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYEAR() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYEAR(String value) {
        this.year = value;
    }

    /**
     * Gets the value of the workgroup property.
     * 
     * @return
     *     possible object is
     *     {@link WORKGROUPType }
     *     
     */
    public WORKGROUPType getWORKGROUP() {
        return workgroup;
    }

    /**
     * Sets the value of the workgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link WORKGROUPType }
     *     
     */
    public void setWORKGROUP(WORKGROUPType value) {
        this.workgroup = value;
    }

    /**
     * Gets the value of the financiers property.
     * 
     * @return
     *     possible object is
     *     {@link FINANCIERSType }
     *     
     */
    public FINANCIERSType getFINANCIERS() {
        return financiers;
    }

    /**
     * Sets the value of the financiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link FINANCIERSType }
     *     
     */
    public void setFINANCIERS(FINANCIERSType value) {
        this.financiers = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link COMMENTSType }
     *     
     */
    public COMMENTSType getCOMMENTS() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMMENTSType }
     *     
     */
    public void setCOMMENTS(COMMENTSType value) {
        this.comments = value;
    }

    /**
     * Gets the value of the foreword property.
     * 
     * @return
     *     possible object is
     *     {@link FOREWORDType }
     *     
     */
    public FOREWORDType getFOREWORD() {
        return foreword;
    }

    /**
     * Sets the value of the foreword property.
     * 
     * @param value
     *     allowed object is
     *     {@link FOREWORDType }
     *     
     */
    public void setFOREWORD(FOREWORDType value) {
        this.foreword = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link INDEXType }
     *     
     */
    public INDEXType getINDEX() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link INDEXType }
     *     
     */
    public void setINDEX(INDEXType value) {
        this.index = value;
    }

    /**
     * Gets the value of the trackChanges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackChanges() {
        return trackChanges;
    }

    /**
     * Sets the value of the trackChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackChanges(String value) {
        this.trackChanges = value;
    }

}
